In [1]:
#ARRAY CREATION & PROPERTIES
#CREATING 1D ARRAY
import numpy as np
arr1D=np.array([10,20,30,40,50])
#CREATING 2D ARRAY
arr2D=np.array([[1,2,3],[4,5,6]])
#CREATING 3D ARRAY
arr3D=np.array([[[11,33,55],[22,44,66],[33,55,77]]])
#SHAPE OF ARRAYS
print("shape of array:",arr1D.shape)
print("shape of array:",arr2D.shape)
print("shape of array:",arr3D.shape)
#SIZE OF ARRAYS
print("size of array:",arr1D.size)
print("size of array:",arr2D.size)
print("size of array:",arr3D.size)
#DATATPYE
print("datatype:",arr1D.dtype)
print("datatype:",arr2D.dtype)
print("datatype:",arr3D.dtype)
#DIMENSIONS OF ARRAYS
print("dimension:",np.ndim(arr1D))
print("dimension:",np.ndim(arr2D))
print("dimension:",np.ndim(arr3D))
print("arr1D elements=",arr1D)
print("arr2D elements=",arr2D)
print("arr3D elements=",arr3D)
#IDENTITY
print("Identity matrix:",np.identity(4))
# EYE-DIAGONAL IDENTITY MATRIX
print("Eye matrix:",np.eye(2))


shape of array: (5,)
shape of array: (2, 3)
shape of array: (1, 3, 3)
size of array: 5
size of array: 6
size of array: 9
datatype: int64
datatype: int64
datatype: int64
dimension: 1
dimension: 2
dimension: 3
arr1D elements= [10 20 30 40 50]
arr2D elements= [[1 2 3]
 [4 5 6]]
arr3D elements= [[[11 33 55]
  [22 44 66]
  [33 55 77]]]
Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Eye matrix: [[1. 0.]
 [0. 1.]]
