In [1]:
#7.BROADCASTING
import numpy as np
arr1D=np.array([[10,20,30],[40,50,60]])
arr2D=np.array([[1,2,3],[4,5,6]])
print(arr1D)
print(arr2D)
print("arr+scalar:",arr1D+6)
print("Adding Arrays=:",arr1D+arr2D)


[[10 20 30]
 [40 50 60]]
[[1 2 3]
 [4 5 6]]
arr+scalar: [[16 26 36]
 [46 56 66]]
Adding Arrays=: [[11 22 33]
 [44 55 66]]
