In [1]:
#16.PERFORM THE FOLLOWING OPERATIONS ON MULTIPLE ARRAYS
import numpy as np
arr1=np.array([[2,4,5],[2,8,7]])
arr2=np.array([[1,6,2],[2,6,4]])
print("vertically stacked:\n",np.vstack((arr1,arr2)))
print("horizontally stacked:\n",np.hstack((arr1,arr2)))


vertically stacked:
 [[2 4 5]
 [2 8 7]
 [1 6 2]
 [2 6 4]]
horizontally stacked:
 [[2 4 5 1 6 2]
 [2 8 7 2 6 4]]
