In [1]:
#12.PERFORM THE FOLLOWING SORTING METHODS
import numpy as np
a=np.array([1,2,3,4,5])
a1=np.array([5,4,3,2,1])
a2=np.array([3,5,4,1,2])
print(np.argsort(a))
print(np.argsort(a1))
print(np.argsort(a2))
print(np.sort(a1))
print(np.unique(a2))


[0 1 2 3 4]
[4 3 2 1 0]
[3 4 0 2 1]
[1 2 3 4 5]
[1 2 3 4 5]
