In [1]:
#8.UNIVERSAL FUNCTIONS
#→Arithematic functions
import numpy as np
arr1=np.array([[1,2,3],[6,7,8]])
arr2=np.array([[4,7,6],[3,7,1]])
print("Addition:\n",np.add(arr1,arr2))
print("Subtraction:\n",np.subtract(arr1,arr2))
print("Multiplication:\n",np.multiply(arr1,arr2))
print("Division:\n",np.divide(arr1,arr2))
#→Trigonometric functions
import numpy as np
angles_degrees=np.array([120,35,180])
angles_radians=np.radians(angles_degrees)
print("sine:\n",np.sin(angles_radians))
print("cosine:\n",np.cos(angles_radians))
print("tangent:\n",np.tan(angles_radians))
print("convert degrees to radians",np.radians(angles_degrees))
#→Exponential & logarithmic functions
import numpy as np
arr1=np.array([1,2,3,6,7])
print('exponential of elements',np.exp(arr1))
print("natural logrithm of elements",np.log(arr1))
print("log base 10 of elemnts",np.log10(arr1))
#—>Rounding functions
import numpy as np
a=np.array([1.9,2.4,3.6,4.9])
print("floor of elements",np.floor(a))
print("ceil of elements",np.ceil(a))
print("round of elements",np.round(a, decimals=1))


Addition:
 [[ 5  9  9]
 [ 9 14  9]]
Subtraction:
 [[-3 -5 -3]
 [ 3  0  7]]
Multiplication:
 [[ 4 14 18]
 [18 49  8]]
Division:
 [[0.25       0.28571429 0.5       ]
 [2.         1.         8.        ]]
sine:
 [8.66025404e-01 5.73576436e-01 1.22464680e-16]
cosine:
 [-0.5         0.81915204 -1.        ]
tangent:
 [-1.73205081e+00  7.00207538e-01 -1.22464680e-16]
convert degrees to radians [2.0943951  0.61086524 3.14159265]
exponential of elements [   2.71828183    7.3890561    20.08553692  403.42879349 1096.63315843]
natural logrithm of elements [0.         0.69314718 1.09861229 1.79175947 1.94591015]
log base 10 of elemnts [0.         0.30103    0.47712125 0.77815125 0.84509804]
floor of elements [1. 2. 3. 4.]
ceil of elements [2. 3. 4. 5.]
round of elements [1.9 2.4 3.6 4.9]
